Repository NoroffFEU/edu-gate, pull requests merged in 2025-01, with the labels that each got.

#214 added pic, button and text to the page
  templates/index.html
Labels: code

#235 Buttons
  css/style.css
Labels: code

#238 Update README.md command and error
  README.md
Labels: documentation

#244 added padding and margin to footer
  css/style.css
  templates/footer.html
Labels: code

#251 deleted footer.html and added footer tailwind css to the index.html
  templates/footer.html
  templates/index.html
Labels: CSS, code

#242 created admin edit page
  templates/edit-profile-admin.html
Labels: HTML, code

#263 changed the link for stylesheet css
  templates/edit-profile-admin.html
  templates/edit-profile-student.html
Labels: code

#243 html for add teacher page
  templates/add-teachers.html
  templates/teacher.html
Labels: HTML, code

#268 Update dashboard-admin.html
  templates/dashboard-admin.html
Labels: code

#269 Update dashboard-admin.html
  templates/dashboard-admin.html
Labels: code

#278 Update dashboard-teacher.html
  templates/dashboard-teacher.html
Labels: code

#281 Update dashboard-student.html
  templates/dashboard-student.html
Labels: code

#300 custom classes and correcting primary color
  css/styles.css
  templates/contact.html
Labels: CSS

#280 Update dashboard-admin.html
  templates/dashboard-admin.html
Labels: code

#298 Dashboard teacher html
  public/img/Student initials mobile.png
  public/img/Student initials.png
  templates/dashboard-admin.html
  templates/dashboard-teacher.html
  templates/manage-user.html
Labels: CSS, code
