Repository NoroffFEU/edu-gate, pull requests merged in 2025-03, with the labels that each got.

#410 Added header to add-teachers.html
  templates/add-teachers.html
Labels: HTML

#435 User story 1 add students page anna k
  templates/add-students-new.html
Labels: HTML

#443 Added footer to add-teachers.html
  templates/add-teachers.html
Labels: HTML

#463 Issue 395 Completed, awaiting QA approval.
  package-lock.json
  templates/registration-page.html
Labels: QA APPROVAL

#449 Applied font-Roboto and font-Poppins to missing elements
  templates/add-teachers.html
Labels: HTML, CSS

#479 Created the template for the error alert
  public/icons/vector.png
  public/icons/x-red.png
  templates/sign-up.html
Labels: QA APPROVAL, AURLAND

#481 480 user story 3 implement form validation messages to signup page for mobile mr
  templates/sign-up.html
Labels: QA APPROVAL, AURLAND

#459 385 User Story 1: Implement a pixel perfect landing page for desktop - Team Aurland
  templates/index.html
Labels: QA APPROVAL, AURLAND

#442 recreated the branch
  templates/your-results.html
Labels: HTML, CSS

#467 Added header, hrefs inside buttons and footer
  templates/sign-up.html
Labels: QA APPROVAL, AURLAND

#560 Update student-profile.html
  templates/student-profile.html
Labels: QA APPROVAL, viking

#462 User story 1 sidebar add students page annak
  templates/add-students-new.html
Labels: HTML

#561 Fixing the code structure.
  templates/edit-profile-student.html
Labels: HTML, QA APPROVAL, viking

#466 Fixed commit
  package-lock.json
  package.json
  public/icons/x-close(1).jpg
  templates/index.html
Labels: QA APPROVAL, AURLAND

#562 User story 3 create html page annak
  templates/manage-user-student.html
  templates/manage-user-teacher.html
Labels: HTML

#550 Pixel perfect login page
  templates/login-page.html
  templates/registration-page.html
Labels: QA APPROVAL, AURLAND

#584 Create and Style the Update Button: Issue 527
  package-lock.json
  templates/students/edit-profile-student.html
Labels: QA APPROVAL, viking

#611 User story 2 add teachers page anna k
  templates/teachers/add-teachers.html
Labels: HTML, CSS

#579 Implement the Success Modal - Issue: 544
  package-lock.json
  public/icons/green-x.png
  public/icons/success.png
  templates/modals/modals.html
Labels: QA APPROVAL, AURLAND

#608 Fixing the login & register page.
  templates/login-page.html
  templates/registration-page.html
Labels: QA APPROVAL, AURLAND

#607 Recommiting sign up page error template
  templates/sign-up.html
Labels: QA APPROVAL, AURLAND

#627 Implemented accessibility features
  templates/students/student-profile.html
Labels: QA APPROVAL, viking

#628 Profile Image Update
  templates/admins/admin-profile.html
Labels: QA APPROVAL, viking

#633 Implement the student result edit modal 546 mr
  package-lock.json
  templates/modals/modals.html
Labels: QA APPROVAL, AURLAND
